$env:PATH = "C:\msys64\ucrt64\bin;C:\msys64\usr\bin;$env:PATH"
$ws = $PSScriptRoot
$glfw = "$ws\third_party"

# ============================================================
# 步骤 1：生成内嵌着色器头文件
# ============================================================
Write-Host "Generating embedded shader header..."
$enc = [System.Text.Encoding]::UTF8

function EmbedFile($filePath) {
    return [System.IO.File]::ReadAllText($filePath, $enc)
}

$vertSrc       = EmbedFile("$ws\shaders\vert.glsl")
$fragHeaderSrc = EmbedFile("$ws\shaders\frag_desktop_header.glsl")
$blackholeSrc  = EmbedFile("$ws\blackhole.glsl")

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated by build script - DO NOT EDIT")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")

# 使用 C++11 原始字符串字面量 R"DELIM(...)DELIM" 避免转义问题
[void]$sb.Append('inline const char* g_vert_src = R"EMBED_BH(')
[void]$sb.Append("`n")
[void]$sb.Append($vertSrc)
[void]$sb.Append("`n")
[void]$sb.AppendLine(')EMBED_BH";')
[void]$sb.AppendLine("")

[void]$sb.Append('inline const char* g_frag_header_src = R"EMBED_BH(')
[void]$sb.Append("`n")
[void]$sb.Append($fragHeaderSrc)
[void]$sb.Append("`n")
[void]$sb.AppendLine(')EMBED_BH";')
[void]$sb.AppendLine("")

[void]$sb.Append('inline const char* g_blackhole_src = R"EMBED_BH(')
[void]$sb.Append("`n")
[void]$sb.Append($blackholeSrc)
[void]$sb.Append("`n")
[void]$sb.AppendLine(')EMBED_BH";')

[System.IO.File]::WriteAllText("$ws\build\embedded_shaders.h", $sb.ToString(), $enc)
Write-Host "  -> build/embedded_shaders.h"

# ============================================================
# 步骤 2：编译资源文件（包含图标）
# ============================================================
Write-Host "Compiling resource file..."
& windres --output-format=coff --input-format=rc -o "$ws\build\resource.o" "$ws\resource.rc" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "windres failed, continuing without icon..."
}

# ============================================================
# 步骤 3：静态链接编译（-static 消除所有 MinGW DLL 依赖）
# ============================================================
Write-Host "Compiling main program (static linking)..."
$resourceFile = if (Test-Path "$ws\build\resource.o") { "$ws\build\resource.o" } else { "" }

$compileArgs = @(
    "-std=c++17", "-O2", "-static",
    "-o", "$ws\build\blackhole.exe",
    "$ws\src\main.cpp",
    "$ws\src\capture_wgc.cpp",
    "$ws\src\capture_dxgi.cpp",
    "$ws\src\gl_texture.cpp",
    "$ws\src\gui_config.cpp",
    "$ws\src\win32_gl.cpp",
    "$ws\src\imgui\imgui.cpp",
    "$ws\src\imgui\imgui_draw.cpp",
    "$ws\src\imgui\imgui_widgets.cpp",
    "$ws\src\imgui\imgui_tables.cpp",
    "$ws\src\imgui\imgui_impl_glfw.cpp",
    "$ws\src\imgui\imgui_impl_opengl3.cpp"
)
if ($resourceFile) { $compileArgs += $resourceFile }

$compileArgs += @(
    "-I", "$ws\build",
    "-I", "$ws\src\imgui",
    "-I", "$glfw\include",
    "-I", "C:\msys64\ucrt64\include",
    "-L", "$glfw\lib-mingw-w64",
    "-L", "C:\msys64\ucrt64\lib",
    "-lglfw3", "-lopengl32", "-lgdi32", "-ld3d11", "-ldxgi",
    "-lruntimeobject", "-ldwmapi", "-lcomctl32", "-lole32",
    "-mwindows"
)

& g++ @compileArgs 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "BUILD SUCCESS - standalone blackhole.exe (single file, no DLLs needed)"
    Get-Item "$ws\build\blackhole.exe" | Select-Object Length, LastWriteTime
} else {
    Write-Host "BUILD FAILED (exit $LASTEXITCODE)"
}

# 清理
Remove-Item "$ws\build\resource.o" -Force -ErrorAction SilentlyContinue
Remove-Item "$ws\build\embedded_shaders.h" -Force -ErrorAction SilentlyContinue
